$outputFile = "install.lua"
$header = "-- Arcade OS Installer
-- Generated by bundle.ps1

local function writeFile(path, content)
    local file = fs.open(path, 'w')
    file.write(content)
    file.close()
    print('Installed: ' .. path)
end

print('Installing Arcade OS...')
"

Set-Content -Path $outputFile -Value $header

$files = Get-ChildItem -Filter "*.lua" | Where-Object { $_.Name -ne "install.lua" -and $_.Name -ne "bundle.ps1" }

foreach ($file in $files) {
    $content = Get-Content $file.FullName -Raw
    
    # Determine appropriate delimiter
    $level = 0
    $open = "[" + "=" * $level + "["
    $close = "]" + "=" * $level + "]"
    
    while ($content.Contains($close)) {
        $level++
        $open = "[" + "=" * $level + "["
        $close = "]" + "=" * $level + "]"
    }
    
    $luaBlock = "writeFile('$($file.Name)', $open
$content
$close)
"
    Add-Content -Path $outputFile -Value $luaBlock
}

$footer = "
print('Installation Complete!')
print('Rebooting in 2 seconds...')
sleep(2)
os.reboot()
"
Add-Content -Path $outputFile -Value $footer

Write-Host "Build complete: $outputFile"
